# Generated by Django 3.2.6 on 2021-08-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_orderitem_review_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
    ]
