# Generated by Django 3.2.6 on 2021-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
